#!/usr/bin/env node
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * keymouse-adapter — handler.js
 *
 * UI 自动化脚本生成 + 回放适配器。
 * 多后端：KeymouseGo / AutoHotkey / TinyTask
 * 同一套动作描述 → 不同格式脚本
 *
 * 输入:
 * {
 *   actions: [{ type, ... }],
 *   backend: "keymousego" | "ahk" | "tinytask",
 *   mode: "generate" | "replay",
 *   outputDir: "./scripts"
 * }
 *
 * 动作类型:
 *   click     { x, y, button?, count? }
 *   move      { x, y, duration? }
 *   key       { keys, duration? }
 *   text      { text }
 *   wait      { ms }
 *   scroll    { x, y, amount? }
 *   screenshot{ name? }
 *   loop      { count, actions: [...] }
 *
 * 用法: node handler.js <input-json> | cat input.json | node handler.js
 */


import fs from 'fs'; 
import path from 'path'; 
import { execSync } from 'child_process';

function main() {
  let i; const a = process.argv[2];
  if (a && a !== '--') { try { i = JSON.parse(fs.readFileSync(path.resolve(a), 'utf-8')); } catch (e) { return out('ERROR', 'Read: ' + e.message); } }
  else { const c = []; process.stdin.on('data', d => c.push(d)); process.stdin.on('end', () => { try { i = JSON.parse(Buffer.concat(c).toString()); h(i); } catch (e) { out('ERROR', 'Parse: ' + e.message); } }); return; }
  h(i);
}

function h(input) {
  const actions = input.actions || [];
  const backend = input.backend || 'keymousego';
  const mode = input.mode || 'generate';
  const outputDir = path.resolve(input.outputDir || '.soma-automation');
  const scriptName = input.name || `auto_${Date.now()}`;

  if (actions.length === 0) return out('ERROR', 'actions[] required (at least one click/key/wait)');

  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  let scriptContent, scriptExt, backendName;

  switch (backend) {
    case 'keymousego': {
      // KeymouseGo JSON5 format
      const records = [];
      for (const a of actions) {
        switch (a.type) {
          case 'click': records.push({ type: 'click', x: a.x || 0, y: a.y || 0, button: a.button || 'left', count: a.count || 1, delay: a.delay || 100 }); break;
          case 'move': records.push({ type: 'move', x: a.x || 0, y: a.y || 0, delay: a.duration || 50 }); break;
          case 'key': records.push({ type: 'key', keys: Array.isArray(a.keys) ? a.keys : [a.keys || ''], delay: a.duration || 50 }); break;
          case 'text': records.push({ type: 'text', text: a.text || '', delay: a.duration || 30 }); break;
          case 'wait': records.push({ type: 'wait', delay: a.ms || 1000 }); break;
          case 'scroll': records.push({ type: 'scroll', x: a.x || 0, y: a.y || 0, amount: a.amount || 3 }); break;
          case 'screenshot': records.push({ type: 'screenshot', name: a.name || 'screenshot' }); break;
          case 'loop': {
            for (let i = 0; i < (a.count || 1); i++) {
              if (a.actions) a.actions.forEach(sub => { sub.type && h({ ...input, actions: [sub], outputDir, mode: 'silent' }); });
            }
            break;
          }
        }
      }
      scriptContent = JSON.stringify(records, null, 2);
      scriptExt = '.json5';
      backendName = 'KeymouseGo';
      break;
    }

    case 'ahk': {
      // AutoHotkey script
      let ahk = `; Auto-generated by Soma keymouse-adapter\n; Script: ${scriptName}\n\n`;
      for (const a of actions) {
        switch (a.type) {
          case 'click': ahk += `MouseClick, ${a.button || 'left'}, ${a.x || 0}, ${a.y || 0}, ${a.count || 1}\nSleep, ${a.delay || 100}\n`; break;
          case 'move': ahk += `MouseMove, ${a.x || 0}, ${a.y || 0}\nSleep, ${a.duration || 50}\n`; break;
          case 'key': ahk += `Send, {${(Array.isArray(a.keys) ? a.keys : [a.keys]).join(' ')}}\nSleep, ${a.duration || 50}\n`; break;
          case 'text': ahk += `Send, ${a.text || ''}\n`; break;
          case 'wait': ahk += `Sleep, ${a.ms || 1000}\n`; break;
          case 'scroll': ahk += `MouseClick, WheelDown, ${a.x || 0}, ${a.y || 0}, ${a.amount || 3}\n`; break;
        }
      }
      ahk += '\nReturn\n';
      scriptContent = ahk;
      scriptExt = '.ahk';
      backendName = 'AutoHotkey';
      break;
    }

    case 'tinytask': {
      // TinyTask uses binary .exe files — can't generate directly.
      // Instead, generate a human-readable instruction + KeymouseGo fallback
      scriptContent = `; TinyTask does not support text-based scripts.\n; Record manually or use KeymouseGo backend instead.\n;\n; Intended actions:\n${JSON.stringify(actions, null, 2)}`;
      scriptExt = '.txt';
      backendName = 'TinyTask (manual only)';
      break;
    }

    default:
      return out('ERROR', `Unknown backend: ${backend}. Valid: keymousego, ahk, tinytask`);
  }

  const scriptFile = path.join(outputDir, `${scriptName}${scriptExt}`);
  fs.writeFileSync(scriptFile, scriptContent, 'utf-8');

  // Replay mode: try to invoke the tool
  let replayResult = null;
  if (mode === 'replay') {
    try {
      if (backend === 'keymousego') {
        // Try to find KeymouseGo and run
        try {
          const result = execSync(`python -m keymousego "${scriptFile}"`, { encoding: 'utf-8', timeout: 30000, stdio: 'pipe' });
          replayResult = { ok: true, output: result.slice(0, 200) };
        } catch (e) {
          replayResult = { ok: false, error: 'KeymouseGo not found. Install: git clone https://github.com/taojy123/KeymouseGo' };
        }
      } else if (backend === 'ahk') {
        try {
          execSync(`start "" "${scriptFile}"`, { encoding: 'utf-8', timeout: 5000 });
          replayResult = { ok: true, output: 'AutoHotkey script launched' };
        } catch (e) {
          replayResult = { ok: false, error: 'AutoHotkey not found' };
        }
      }
    } catch (e) { replayResult = { ok: false, error: e.message.slice(0, 100) }; }
  }

  return out('PASS', `Script generated: ${scriptName}${scriptExt} (${backendName})`, {
    scriptFile, backend, backendName, actionCount: actions.length, actionTypes: [...new Set(actions.map(a => a.type))], replayResult, downloadUrl: backend === 'keymousego' ? 'https://github.com/taojy123/KeymouseGo' : backend === 'ahk' ? 'https://www.autohotkey.com/' : null,
  });
}

function out(r, s, d) { console.log(JSON.stringify({ softill: 'keymouse-adapter', result: r, summary: s, data: d || {}, evidence: [] }, null, 2)); process.exit(r === 'PASS' ? 0 : 1); }


// ESM CLI entry point
const isCLI = process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (isCLI) main();