#!/usr/bin/env node
import { fileURLToPath } from 'url';
import { dirname, resolve } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/**
 * worktree-create — handler.js
 *
 * Create git worktree for task isolation, set up session config and prompts
 * 级别: L3_write
 * 生成: meta-softill blueprint (v0.2 七面元器)
 */


import fs from 'fs';

import path from 'path';

function handle(input, context) {
  const taskId = input.taskId;
  const goal = input.goal || '';
  const role = input.role || 'worker';
  const repoRoot = input.repoRoot || process.cwd();
  const worktreeBase = input.worktreeBase || path.resolve(repoRoot, '..', '..', 'Worktrees', 'somaos-combo-lab');
  const baseCommit = input.baseCommit || '';
  const reportPath = input.reportPath || `tasks/reports/${taskId}.md`;

  // Validate required inputs
  const errors = [];
  if (!taskId) errors.push('taskId is required');
  if (!goal) errors.push('goal is required');
  if (errors.length > 0) {
    return { result: 'BLOCKED', reason: errors.join('; '), evidence: [] };
  }

  const worktreePath = path.resolve(worktreeBase, taskId);

  try {
    // Create worktree directory structure
    fs.mkdirSync(worktreePath, { recursive: true });
    fs.mkdirSync(path.join(worktreePath, '.soma'), { recursive: true });
    fs.mkdirSync(path.join(worktreePath, '.claude', 'rules'), { recursive: true });

    // Write session config
    const session = {
      branch: `task/${taskId}`,
      repoRoot: repoRoot,
      worktreeRoot: worktreePath,
      project: 'somaos-combo-lab',
      role: role,
      taskId: taskId,
      createdAt: new Date().toISOString(),
      baseCommit: baseCommit,
    };
    fs.writeFileSync(path.join(worktreePath, '.soma', 'session.json'),
      JSON.stringify(session, null, 2), 'utf-8');

    // Write initial prompt
    const fullPrompt = `${goal}\n\n完成后将结论写入 ${reportPath}`;
    fs.writeFileSync(path.join(worktreePath, '.initial-prompt.txt'), fullPrompt, 'utf-8');

    // Write dispatch rules
    const rules = [
      '# Worktree Hard Rules — Auto-generated by dispatch-combo',
      `# Task: ${taskId}`,
      '',
      '=== [A] 禁止派生子任务 ===',
      '=== [B] 禁止 Agent/Bash后台/ScheduleWakeup ===',
      '=== [C] 禁止使用 Agent/Workflow 等子智能体工具 ===',
      '=== [D] 禁止调用 LLM API ===',
      '=== [E] 子 Worker 权限不得超过父 Combo ===',
      '',
      '完成后必须将结论写入 output_report',
    ].join('\n');
    fs.writeFileSync(path.join(worktreePath, '.claude', 'rules', 'dispatch-rules.md'), rules, 'utf-8');

    // Write CLAUDE.local.md
    const localMd = [
      '# CLAUDE.local.md — Foundry Session (GIT_WORKTREE)',
      `# Task: ${taskId}`,
      `# Role: ${role}`,
      '# Auto-generated by dispatch-combo',
      '',
      '## Write Boundary',
      `Allowed: ${worktreePath}`,
      `Protected: ${worktreePath}/CLAUDE.md`,
      '',
      '## Role Restrictions',
      '### Worker Permissions',
      '✅ Modify files within this worktree',
      '❌ Write outside worktree',
      '❌ Merge to main',
    ].join('\n');
    fs.writeFileSync(path.join(worktreePath, 'CLAUDE.local.md'), localMd, 'utf-8');

    return {
      result: 'PASS',
      worktreePath: worktreePath,
      session: session,
      filesCreated: [
        '.soma/session.json',
        '.initial-prompt.txt',
        '.claude/rules/dispatch-rules.md',
        'CLAUDE.local.md',
      ],
      evidence: [
        { type: 'worktree_created', path: worktreePath, taskId: taskId },
      ],
    };
  } catch (err) {
    return {
      result: 'ERROR',
      reason: `Failed to create worktree: ${err.message}`,
      evidence: [{ type: 'error', message: err.message }],
    };
  }
}

// ═════════════════════════════════════════════════════
// CLI 入口
// ═════════════════════════════════════════════════════

function main() {
  let input;
  if (process.argv[2] && process.argv[2] !== '--') {
    const p = path.resolve(process.argv[2]);
    try { input = JSON.parse(fs.readFileSync(p, 'utf-8')); }
    catch (e) { return fail(`Read fail: ${e.message}`); }
  } else if (!process.stdin.isTTY) {
    const chunks = [];
    process.stdin.on('data', c => chunks.push(c));
    process.stdin.on('end', () => {
      try { input = JSON.parse(Buffer.concat(chunks).toString()); run(input); }
      catch (e) { fail(`Parse error: ${e.message}`); }
    });
    return;
  } else {
    input = { input: process.argv[2] || '' };
  }
  run(input);
}

function run(input) {
  const result = handle(input, {});
  const status = result.result === 'PASS' ? 'PASS' :
                 result.result === 'BLOCKED' ? 'BLOCKED' : 'ERROR';
  const code = status === 'PASS' ? 0 : 1;
  const ev = result.evidence || [];
  console.log(JSON.stringify({
    softill: 'worktree-create',
    result: status,
    summary: result.reason || (status === 'PASS' ? `Worktree created at ${result.worktreePath}` : ''),
    data: result,
    evidence: ev,
    meta: { name: 'worktree-create', level: 'L3_write', v: '0.2.0' },
  }, null, 2));
  process.exit(code);
}

function fail(msg) {
  console.log(JSON.stringify({ softill: 'worktree-create', result: 'ERROR', summary: msg, data: {}, evidence: [] }));
  process.exit(1);
}

export default { handle };



// ESM CLI entry point
const isCLI = process.argv[1] && resolve(process.argv[1]) === resolve(fileURLToPath(import.meta.url));
if (isCLI) main();