#!/usr/bin/env node
/**
 * api-client-generator — handler.js
 *
 * 从后端契约生成前端 API client 代码。
 * 只生成草稿，写入 generated/，不覆盖业务代码。
 *
 * 遵循 Tauri 规则：每 command 对应一个 api client，强制 input/output 类型。
 *
 * 输入: { endpoints: [{method, path, ...}], outputDir?: string, style?: "fetch"|"axios"|"request" }
 * 输出: { generated: [{file, content preview}], count }
 *
 * 用法: node handler.js <input-json> | cat input.json | node handler.js
 */

const fs = require('fs');
const path = require('path');

function main() {
  let input;
  if (process.argv[2] && process.argv[2] !== '--') {
    const p = path.resolve(process.argv[2]);
    try { input = JSON.parse(fs.readFileSync(p, 'utf-8')); } catch (e) { return out('ERROR', `Read fail: ${e.message}`); }
  } else {
    const chunks = [];
    process.stdin.on('data', c => chunks.push(c));
    process.stdin.on('end', () => {
      try { input = JSON.parse(Buffer.concat(chunks).toString()); handle(input); } catch (e) { out('ERROR', `Parse error: ${e.message}`); }
    });
    return;
  }
  handle(input);
}

function handle(input) {
  const endpoints = input.endpoints || [];
  const outputDir = path.resolve(input.outputDir || 'generated');
  const style = input.style || 'fetch';

  if (endpoints.length === 0) return out('ERROR', 'endpoints[] required (from api-contract-extractor)');

  const generated = [];
  let indexImports = [];

  // Group by path prefix for file organization
  const groups = {};
  for (const ep of endpoints) {
    const prefix = ep.path.split('/').filter(Boolean)[0] || 'root';
    if (!groups[prefix]) groups[prefix] = [];
    groups[prefix].push(ep);
  }

  // Ensure output directory
  if (!fs.existsSync(outputDir)) fs.mkdirSync(outputDir, { recursive: true });

  for (const [group, eps] of Object.entries(groups)) {
    const fileName = `${group}.ts`;
    const filePath = path.join(outputDir, fileName);
    let functions = [];
    let imports = new Set();

    for (const ep of eps) {
      const fnName = toCamelCase(ep.handler || ep.path.split('/').filter(Boolean).pop() || 'endpoint');
      const method = ep.method.toLowerCase();
      const hasBody = ['post', 'put', 'patch'].includes(method) || ep.requestBody?.inferred;
      const typeName = toPascalCase(fnName) + (hasBody ? 'Input' : 'Params');
      const respType = toPascalCase(fnName) + 'Response';

      if (style === 'fetch') {
        imports.add('// Uses native fetch — no import needed');
        functions.push(generateFetch(fnName, method, ep.path, hasBody, typeName, respType));
      } else if (style === 'axios') {
        imports.add("import axios from 'axios';");
        functions.push(generateAxios(fnName, method, ep.path, hasBody, typeName, respType));
      } else {
        functions.push(generateRequest(fnName, method, ep.path, hasBody, typeName, respType));
      }
    }

    const fileContent = `// Auto-generated by api-client-generator
// Do not edit directly — regenerate when backend contract changes
${[...imports].join('\n')}

${functions.join('\n\n')}
`;

    fs.writeFileSync(filePath, fileContent, 'utf-8');
    indexImports.push(`export * from './${fileName.replace('.ts', '')}';`);
    generated.push({
      file: fileName,
      functions: functions.length,
      preview: functions.slice(0, 2).map(f => f.split('\n').slice(0, 3).join('\n')).join('\n'),
    });
  }

  // Generate index.ts
  if (generated.length > 1) {
    const indexPath = path.join(outputDir, 'index.ts');
    fs.writeFileSync(indexPath, indexImports.join('\n') + '\n', 'utf-8');
    generated.push({ file: 'index.ts', functions: 0, preview: 're-export' });
  }

  return out('PASS', `${generated.length} files with ${endpoints.length} API functions generated`, {
    generated,
    endpointCount: endpoints.length,
    outputDir,
    style,
    fileCount: generated.length,
    groups: Object.keys(groups),
  });
}

function generateFetch(name, method, endpoint, hasBody, typeName, respType) {
  const bodyArg = hasBody ? `, body?: ${typeName}` : '';
  const bodyCode = hasBody ? `\n    body: JSON.stringify(body),\n    headers: { 'Content-Type': 'application/json' },` : '';
  return `export async function ${name}(input${bodyArg}): Promise<${respType}> {
  const response = await fetch('${endpoint}', {
    method: '${method.toUpperCase()}',${bodyCode}
  });
  if (!response.ok) throw new Error(\`${name} failed: \${response.status}\`);
  return response.json();
}`.replace(/  /g, '  ');
}

function generateAxios(name, method, endpoint, hasBody, typeName, respType) {
  const bodyArg = hasBody ? `, body?: ${typeName}` : '';
  const bodyRef = hasBody ? ', body' : '';
  return `export async function ${name}(input${bodyArg}): Promise<${respType}> {
  const response = await axios.${method}('${endpoint}'${bodyRef});
  return response.data;
}`;
}

function generateRequest(name, method, endpoint, hasBody, typeName, respType) {
  // Generic request wrapper (Tauri-style or custom)
  const bodyArg = hasBody ? `, body?: ${typeName}` : '';
  const bodyRef = hasBody ? ', body' : '';
  return `/** ${method.toUpperCase()} ${endpoint} */\nexport async function ${name}(input${bodyArg}): Promise<${respType}> {
  return request('${method}', '${endpoint}'${bodyRef});
}`;
}

function toCamelCase(s) {
  return s.replace(/[-_\/\s]+(.)/g, (_, c) => c.toUpperCase()).replace(/^[A-Z]/, c => c.toLowerCase()).replace(/[^a-zA-Z0-9]/g, '') || 'apiCall';
}

function toPascalCase(s) {
  const camel = toCamelCase(s);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function out(result, summary, data) {
  console.log(JSON.stringify({ softill: 'api-client-generator', result, summary, data: data || {}, evidence: [] }, null, 2));
  process.exit(result === 'PASS' ? 0 : 1);
}

if (require.main === module) main();
